import { lazy } from 'react';

const adminRoutes = [
  {
    key: 'admin.index',
    index: true,
    path: 'dashboard',
    Element: lazy(() => import('../pages/dashboard')),
  },
  {
    key: 'admin.order',
    index: true,
    path: 'dashboard/order',
    Element: lazy(() => import('../pages/dashboard/orders')),
  },
  {
    key: 'admin.order',
    index: true,
    path: 'dashboard/order/details',
    Element: lazy(() => import('../pages/dashboard/rider/riderDetails')),
  },
  {
    key: 'admin.rider',
    index: true,
    path: 'dashboard/rider',
    Element: lazy(() => import('../pages/dashboard/rider')),
  },
  {
    key: 'admin.rider.add',
    index: false,
    path: 'dashboard/rider/add',
    Element: lazy(() => import('../pages/dashboard/rider/add')),
  },
  {
    key: 'admin.rider.details',
    index: false,
    path: 'dashboard/rider/:id/info',
    Element: lazy(() => import('../pages/dashboard/rider/riderDetails')),
  },
  {
    key: 'admin.rider.settlement',
    index: false,
    path: 'dashboard/rider/:id/settlement',
    Element: lazy(() => import('../pages/dashboard/rider/settlements')),
  },
  {
    key: 'admin.rider.traking',
    index: true,
    path: 'dashboard/rider/:id/track',
    Element: lazy(() => import('../pages/dashboard/rider/riderTraking')),
  },
  {
    key: 'admin.user',
    index: true,
    path: 'dashboard/user',
    Element: lazy(() => import('../pages/dashboard/user')),
  },
  {
    key: 'admin.user.info',
    index: true,
    path: 'dashboard/user/:id/info',
    Element: lazy(() => import('../pages/dashboard/user/userDetails')),
  },
  {
    key: 'admin.user.charges',
    index: true,
    path: 'dashboard/user/:id/charges',
    Element: lazy(() => import('../pages/dashboard/user/charges')),
  },
  {
    key: 'admin.user.details',
    index: false,
    path: 'dashboard/user/details',
    Element: lazy(() => import('../pages/dashboard/user/userDetails')),
  },
  {
    key: 'admin.report',
    index: true,
    path: 'dashboard/report',
    Element: lazy(() => import('../pages/dashboard/reports')),
  },
  {
    key: 'admin.announcement',
    index: true,
    path: 'dashboard/announcement',
    Element: lazy(() => import('../pages/dashboard/announcements')),
  },
  {
    key: 'admin.state',
    index: true,
    path: 'dashboard/state',
    Element: lazy(() => import('../pages/dashboard/state')),
  },
  {
    key: 'admin.state.add',
    index: true,
    path: 'dashboard/state/add',
    Element: lazy(() => import('../pages/dashboard/state/addState')),
  },
  {
    key: 'admin.city',
    index: true,
    path: 'dashboard/city',
    Element: lazy(() => import('../pages/dashboard/city')),
  },
  {
    key: 'admin.city.add',
    index: false,
    path: 'dashboard/city/add',
    Element: lazy(() => import('../pages/dashboard/city/addCity')),
  },
  {
    key: 'admin.settings',
    index: true,
    path: 'dashboard/settings',
    Element: lazy(() => import('../pages/dashboard/profile')),
  },
  {
    key: 'admin.booking',
    index: true,
    path: 'dashboard/booking',
    Element: lazy(() => import('../pages/dashboard/booking')),
  },
  {
    key: 'admin.booking.invoice',
    index: true,
    path: 'dashboard/booking/:id/invoice',
    Element: lazy(() => import('../pages/dashboard/booking/invoice')),
  },
  {
    key: 'admin.booking.history',
    index: true,
    path: 'dashboard/booking/:id/history',
    Element: lazy(() => import('../pages/dashboard/booking/history')),
  },
  {
    key: 'admin.pickups',
    index: true,
    path: 'dashboard/pickups',
    Element: lazy(() => import('../pages/dashboard/pickups')),
  },
  {
    key: 'admin.pickups.rider',
    index: true,
    path: 'dashboard/pickups/:id/assign-rider',
    Element: lazy(() => import('../pages/dashboard/pickups/assignRider')),
  },
  {
    key: 'admin.pickups.info',
    index: true,
    path: 'dashboard/pickups/:id/info',
    Element: lazy(() => import('../pages/dashboard/pickups/info')),
  },
  {
    key: 'admin.tokens',
    index: true,
    path: 'dashboard/token',
    Element: lazy(() => import('../pages/dashboard/tokens')),
  },
  {
    key: 'admin.tokens.details',
    index: true,
    path: 'dashboard/token/:id/details',
    Element: lazy(() => import('../pages/dashboard/tokens/details')),
  },
  {
    key: 'admin.invoice',
    index: true,
    path: 'dashboard/invoice',
    Element: lazy(() => import('../pages/dashboard/invoice')),
  },
  {
    key: 'rider.salary',
    index: true,
    path: 'dashboard/salary',
    Element: lazy(() => import('../pages/dashboard/salary')),
  },
];
export default adminRoutes;
